# Generated by Django 4.1.2 on 2022-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='autorised',
            field=models.BooleanField(blank=True, default=False, verbose_name='Autorisé'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='ifu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IFU'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, verbose_name='Visible'),
        ),
    ]
