# Generated by Django 4.1.2 on 2022-12-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_entreprise_autorised_entreprise_ifu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date added'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date modification'),
        ),
    ]
