# Generated by Django 4.1.2 on 2022-11-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_entreprise_date_added_entreprise_dateç_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='dateç_last_modified',
            new_name='date_last_modified',
        ),
    ]
