# Generated by Django 4.1.2 on 2022-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
