# Generated by Django 4.1.3 on 2022-12-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='author_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
