# Generated by Django 4.1.3 on 2022-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_comments_user_comments_author_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='picture',
            field=models.ImageField(default=2, upload_to='comment/'),
            preserve_default=False,
        ),
    ]
