# Generated by Django 4.1.3 on 2022-12-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_comments_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author_role',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
