# Generated by Django 4.1.2 on 2022-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_carousel_comments_logo_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='is_black',
            field=models.BooleanField(default=False, verbose_name='Black'),
        ),
    ]
