# Generated by Django 4.0.10 on 2023-05-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
