# Generated by Django 4.1.2 on 2022-12-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_typeservice_delete_offre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CategoryFormation',
                'verbose_name_plural': 'CategoryFormations',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('mode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mode')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('certification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Certification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categoryformation', verbose_name='CategoryFormation')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
    ]
