# Generated by Django 4.1.2 on 2022-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_formation_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='IsPrincipal'),
        ),
        migrations.AddField(
            model_name='formation',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='IsPublic'),
        ),
    ]
