# Generated by Django 4.1.2 on 2022-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_formation_is_principal_formation_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='bande',
            field=models.CharField(choices=[('recommande', 'Recommandé'), ('populaire', 'Populaire'), ('nouveau', 'Nouveau')], default='nouveau', max_length=50, verbose_name='Bande'),
        ),
    ]
